### ISSUE TITLE
typescript error for unused @ts-expect-error

### ISSUE THREAD

**Issue by jasonhollander** [kingyue737/nuxt-echarts#3]
Running with typecheck: true returns the following error:

```
 ERROR(vue-tsc)  Unused '@ts-expect-error' directive.
 FILE  /Users/jh/Code/dashboard/node_modules/nuxt-echarts/dist/runtime/components/VChartIsland.server.vue:23:1

    21 | chart.dispose()
    22 |
  > 23 | // @ts-expect-error release memory
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    24 | chart = null
    25 |
    26 | defineSlots<{ fallback: any }>()
```

Great library, thank you!

**Comment by kingyue737** [comment]
Thank you!
I cannot reproduce it on my side. The `@ts-expect-error` directive should take effect here.

Could you please provide a reproduction? Where does `typecheck: true` come from? 
I run `pnpm nuxt typecheck` in a project importing `nuxt-echarts`, no type error occurs.

**Comment by kingyue737** [comment]
Ah, I got it. Maybe you are not using TypeScript in strict mode. So the directive here is unused. Will fix it soon

**Comment by jasonhollander** [comment]
You got to it before I could come back around.   You are correct, only occurs with strict = false.

Thanks for the quick resolution!
