### ISSUE TITLE
How can I use LinearGradient?

### ISSUE THREAD

**Issue by aka-sham** [kingyue737/nuxt-echarts#8]
Hello,

I have tried the following example from Echarts website https://echarts.apache.org/examples/en/editor.html?c=area-simple&lang=ts and I cannot use echarts.graphic.LinearGradient: how can I import it?

Best Regards,

**Comment by kingyue737** [comment]
Just import it from 'echarts/core'
```ts
import { graphic } from 'echarts/core'
```

You can turn on `Minimal Bundle` to see how the official example import the required module
![image](https://github.com/user-attachments/assets/ccf52716-c80d-440e-9a74-ab633f6c7ea3)

**Comment by aka-sham** [comment]
Thank you!
